type Runtime = import("@astrojs/cloudflare").Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {}
}

/**
 * Worker secrets used by src/pages/webhooks/whatsapp.ts.
 *
 * Declared here rather than in worker-configuration.d.ts, because that file is
 * regenerated by `wrangler types` and the declarations would be dropped.
 *
 * Production:
 *   npx wrangler secret put WHATSAPP_VERIFY_TOKEN
 *   npx wrangler secret put WHATSAPP_APP_SECRET
 *
 * Local dev: put them in `.dev.vars` (gitignored) — see `.dev.vars.example`.
 */
interface Env {
  WHATSAPP_VERIFY_TOKEN: string;
  WHATSAPP_APP_SECRET: string;
}
